version: $(ShortVersion).{build}
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
environment:
  ASPNETCORE_ENVIRONMENT: Staging
  VersionSuffix: rc1
  ShortVersion: 1.0.0
services: 
  - mssql
  - mssql2017
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: |
    if ($isWindows) {
      cd build
      .\build.ps1 -target CalculateCoverage
    }
- sh: >-
    cd build
    
    ./build.sh
artifacts:
- path: build\artifacts\*.nupkg
deploy: off
