version: $(ShortVersion).{build}
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
environment:
  ASPNETCORE_ENVIRONMENT: Staging
  VersionSuffix: rc1
  ShortVersion: 1.0.0
nuget:
  project_feed: true
  disable_publish_on_pr: true
artifacts:
- path: build\artifacts\*.nupkg
deploy: off
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    services: mssql2016
    build_script:
      - ps: >-
          cd build

          .\build.ps1 -target CalculateCoverage --settings_skipverification=true
        
  -
    matrix:
      only:
        - image: Ubuntu
    services: mssql
    init:
      - sh: sqlcmd -S localhost -U SA -P Password12! -Q 'select @@VERSION'
    build_script:
      - sh: >-
          cd build

          ./build.sh
